sss

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,84 +1,120 @@
-# This code is licensed from CircleCI to the user under the MIT license.
-# See here for details: https://circleci.com/developer/orbs/licensing
 version: 2.1
-description: Maven commmand execution and cache management
 
-commands:
-  build-jar:
-    parameters:
-      build-flags:
-        type: string
-        description: Flags for mvn package / mvn deploy
-        default: --settings settings.xml -DskipTests
-      directory:
-        type: string
-        description: Directory to execute the maven build
-        default: '.'
-      circle-branch:
-        type: string
-        description: Permissible Circle branch to maven deploy
-        default: master
+# add your orb below, to be used in integration tests (note: a @dev:alpha
+# release must exist.);
+orbs:
+  maven: circleci/maven@dev:alpha
+  orb-tools: circleci/orb-tools@9.0
+
+executors:
+  machine:
+    machine:
+      image: ubuntu-2004:202201-02
+
+# Pipeline parameters
+parameters:
+  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
+  # job, by default.
+  run-integration-tests:
+    type: boolean
+    default: false
+  dev-orb-version:
+    type: string
+    default: "dev:alpha"
+
+jobs:
+  # This job is an example of an integration testing job.
+  # This job should execute a command from your orb and verify
+  # the output is as expected, otherwise the job should fail.
+  #
+  # Rename this job and add more as needed.
+  #
+  integration-test-1:
+    executor: maven/default
     steps:
+      - checkout
       - run:
-          name: Build JAR
+          name: Check if Maven is installed
           command: |
-            source $BASH_ENV
-            cd << parameters.directory >>
-            if [ "$CIRCLE_BRANCH" == "<< parameters.circle-branch >>" ]
-               then
-                mvn clean deploy << parameters.build-flags >>
-                if find *Service -maxdepth 0 -type d; then
-                  find *Service -maxdepth 0 -type d | while read service_name; do
-                    aws s3 cp ${service_name}/target/spec/openapi.json s3://drift-api-specs/${service_name}.json || echo "failed to push ${service_name} spec to s3"
-                  done
-                fi
-               else
-                mvn clean package << parameters.build-flags >>
+            if [[ $(command -v mvn) == "" ]]; then
+              echo " Maven is not installed "; exit 1;
+            else
+              echo Maven successfully installed.
             fi
+workflows:
+  # This `lint-pack_validate_publish-dev` workflow will run on any commit.
+  lint_pack-validate_publish-dev:
+    unless: << pipeline.parameters.run-integration-tests >>
+    jobs:
+      - orb-tools/lint
+      # pack your orb YAML files to a single orb.yml
+      # validate the orb.yml file to ensure it is well-formed
+      - orb-tools/pack:
+          requires:
+            - orb-tools/lint
 
-  run-tests:
-    steps:
-      - run:
-          name: Run Tests
-          command: |
-            TESTFILES=$(circleci tests glob "**/src/test/**/*.java" | circleci tests split --split-by=timings)
-            TESTFILES=$(echo $TESTFILES | sed -r -e 's/\s(\S+\/)+/,/g' | sed -r -e 's/^(\S+\/)+//g')
-            echo $TESTFILES
-            mvn -Dtest=${TESTFILES} test -DfailIfNoTests=false --settings settings.xml
+      # release dev version of orb, for testing & possible publishing.
+      # orb will be published as dev:alpha and dev:${CIRCLE_SHA1:0:7}.
+      # requires a CircleCI API token to be stored as CIRCLE_TOKEN (default)
+      # https://circleci.com/docs/2.0/managing-api-tokens
+      # store CIRCLE_TOKEN as a project env var or Contexts resource
+      # if using Contexts, add your context below
+      - orb-tools/publish-dev:
+          orb-name: circleci/maven
+          context: orb-publisher
+          requires:
+            - orb-tools/pack
 
-  persist-cache:
-    description: Persist the local .m2 directory based on the pom checksum
-    parameters:
-      key:
-        type: string
-        description: UUID for cached data (once written to, cannot be re-written)
-        default: maven-v2-dependencies-{{ checksum "pom.xml" }}
-    steps:
-      - save_cache:
-          paths:
-            - ~/.m2
-          key: << parameters.key >>
+      # trigger an integration workflow to test the
+      # dev:${CIRCLE_SHA1:0:7} version of your orb
+      - orb-tools/trigger-integration-tests-workflow:
+          name: trigger-integration-dev
+          context: orb-publisher
+          requires:
+            - orb-tools/publish-dev
 
-  restore-cache:
-    description: Restore the .m2 cache for our current pom's checksum
-    parameters:
-      key:
-        type: string
-        description: UUID for cached data (once written to, cannot be re-written)
-        default: maven-v2-dependencies-{{ checksum "pom.xml" }}
-    steps:
-      - restore_cache:
-          keys:
-            - << parameters.key >>
+  # This `integration-tests_prod-release` workflow will only run
+  # when the run-integration-tests pipeline parameter is set to true.
+  # It is meant to be triggered by the "trigger-integration-tests-workflow"
+  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
+  integration-tests_prod-release:
+    when: << pipeline.parameters.run-integration-tests >>
+    jobs:
+      # your integration test jobs go here: essentially, run all your orb's
+      # jobs and commands to ensure they behave as expected. or, run other
+      # integration tests of your choosing
 
-  fetch-from-s3:
-    parameters:
-      key:
-        type: string
-        description: S3 key of gzipped tarball to fetch
-    steps:
-      - run:
-          name: Decompress tarball from S3 into .m2
-          command: |
-            mkdir ~/.m2 || eval "ls ~/.m2"
-            curl --retry 3 --retry-delay 5 -s https://s3.amazonaws.com/<< parameters.key >> | tar -xzC ~/.m2 -f -
+      # an example job
+      - integration-test-1
+      - maven/test:
+          name: test-without-settings
+          test_results_path: sample_app/target/surefire-reports
+          app_src_directory: sample_app
+      - maven/test:
+          name: test-with-settings
+          executor: machine
+          test_results_path: sample_app/target/surefire-reports
+          app_src_directory: sample_app
+          settings_file: $M2_HOME/conf/settings.xml
+
+      # publish a semver version of the orb. relies on
+      # the commit subject containing the text "[semver:patch|minor|major|skip]"
+      # as that will determine whether a patch, minor or major
+      # version will be published or if publishing should
+      # be skipped.
+      # e.g. [semver:patch] will cause a patch version to be published.
+      - orb-tools/dev-promote-prod-from-commit-subject:
+          orb-name: circleci/maven
+          context: orb-publisher
+          add-pr-comment: true
+          bot-token-variable: GHI_TOKEN
+          bot-user: orb-publisher
+          fail-if-semver-not-indicated: true
+          publish-version-tag: false
+          requires:
+            - integration-test-1
+            - test-with-settings
+            - test-without-settings
+          filters:
+            branches:
+              only: master
